baseURL = 'https://dekorasi-rumah-minimalis.netlify.app/'
languageCode = 'id-id'
defaultContentLanguage = 'id'
title = 'Dekorasi Rumah Minimalis'
theme = "ghostwriter"

[author]
    name = "Dapur Jiwa"
    homepage = "https://www.dapurjiwa.com"
    bio = "Pengamat Langit"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "Dekorasi Rumah Minimalis"
    description = "Kami Menyajikan berbagai ide dekorasi rumah minimalis Indonesia untuk kebutuhan desain rumah anda."
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    rss= true
    enableRobotsTXT= true
    searchEngineURL = "https://www.google.com/search"

[Permalinks]
    post = "/:slug/"
